__author__ = 'meng wu'

from datatypes.predicates import Predicate

class AnsicEncoder(object):

    def __init__(self, specDFA, prediction):
        self.prediction_ = prediction

        self.specDFA = specDFA
        self.shieldModel_ = ""
        self.numOfShieldBits_ = 0
        self.tmpCount_ = 0
        self.designModel_ = []
        self.designModelStr_ = ""
        self.inputNames_ = []
        self.outputNames_ = []
        self.assertions = []
        self.count = 0

        self.predicates = dict()
        self.predicates_out = dict()
        self.predicates_lits = set()
        self.predicates_lits_out = set()
        self.hist_len = 10

        for var in self.specDFA.getInputVars():
            self.inputNames_.append(self.specDFA.getVarName(var))
        for var in self.specDFA.getOutputVars():
            self.inputNames_.append(self.specDFA.getVarName(var))

        for var in self.specDFA.getOutputVars():
            var_name = self.specDFA.getVarName(var) + "__1"
            self.outputNames_.append(var_name)


        #prepaer predicates
        predicates = self.specDFA.getPredicates()
        for var_name in predicates:
            predicate_parser = Predicate()
            predicate_parser.tokenize(predicates[var_name])
            predicate_ast = predicate_parser.parse()
            self.predicates[var_name] = predicate_ast
            self.predicates_lits = self.predicates_lits.union(predicate_ast.getLits())
            if var_name + "__1" in self.outputNames_:
                self.predicates_out[var_name] = predicate_ast
                self.predicates_lits_out = self.predicates_lits_out.union(predicate_ast.getLits())

    def get_pred_lits(self, out=False):
        if out:
            return self.predicates_lits_out
        else:
            return self.predicates_lits


    """
    Stores DFA in global variables
    """
    def addShieldModel(self, shieldModel, numOfShieldBits, tmpCount):
        self.shieldModel_ = shieldModel
        self.numOfShieldBits_ = numOfShieldBits
        self.tmpCount_= tmpCount


    """
    Stores DFA in global variables
    """
    def addDesignModel(self, designModel):
        self.designModel_= designModel.split('\n')
        self.designModelStr_= designModel





    """
    Creates entire verilog file, consisting of main, shield, design Module
    and returns result as string
    """
    def getEncodedData(self):


        shield_module = self.encodeShieldModel()
        return shield_module



    """
    Builds an Verilog Module from a given shield model
    """
    def encodeShieldModel(self):

        enc = ""
        enc += self.encode_header()
        enc += self.encode_boolVar()
        enc += self.encode_realVar()
        enc += self.encode_histVar()
        enc += self.encode_template()

        enc += self.encode_func_equal()
        enc += self.encode_func_still()
        enc += self.encode_func_real2bool()
        enc += self.encode_func_updateHis()
        enc += self.encode_func_lp()
        enc += self.encode_func_lr()
        enc += self.encode_model(self.numOfShieldBits_, self.tmpCount_)
        enc += self.encode_transit(self.numOfShieldBits_)
        enc += '  return 0; \n}\n\n'

        enc += self.encode_main_shield()
        return enc


    '''
    Returns header

    '''
    def encode_header(self):
        header = r'''
/*
Do not change this file.
This file is automatically generated by Shield Synthesis tool.
Copyright (c) Meng Wu @2019 
*/
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <memory.h>
#include <setjmp.h>
#include <z3.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include <time.h>


'''
        return header

    def encode_template(self):
        if self.prediction_ == 1:
            template_file = open("inputfiles/template_linear.c")
        elif self.prediction_ == 2:
            template_file = open("inputfiles/template_poly.c")
        else:
            return ''

        template = template_file.read()
        template_file.close()
        return template


    '''
    Returns the declaration of all input and output, temporary, and state variables

    '''
    def encode_boolVar(self):

        var_enc = "struct boolVar{\n"

        #declare input and output variables
        for var_name in self.inputNames_:
            var_enc += "  bool " + var_name + ";  //input\n"
        for var_name in self.outputNames_:
            var_enc += "  bool " + var_name + ";  //output\n"
        var_enc += "};\n\n"


        return var_enc

    def encode_realVar(self):
        var_enc = "struct realVar{\n"

        # declare input and output variables
        for var_name in self.inputNames_:
            if var_name not in self.specDFA.getPredicates():
                var_enc += "  bool " + var_name + ";  //bool input\n"
        for var_name in self.outputNames_:
            if var_name[:-3] not in self.specDFA.getPredicates():
                var_enc += "  bool " + var_name + ";  //bool output\n"

        for var_name in self.predicates_lits:
            var_enc += "  float " + var_name + ";  //real variables input\n"
        for var_name in self.predicates_lits_out:
            var_enc += "  float " + var_name + "__1;  //real variables output\n"

        var_enc += "  int result; //for testing\n};\n\n"

        return var_enc

    def encode_histVar(self):
        var_enc = "struct hist_t{\n"
        for var_name in self.predicates_lits_out:
            var_enc += "  float " + var_name + "__1[" + str(self.hist_len)+"];\n"
        var_enc += "};\n\n"
        return var_enc

    def encode_func_equal(self):
        func_enc = "bool equal(struct boolVar *var){\n  return  "

        placeholder = '('
        for var_name in self.outputNames_:
            func_enc += placeholder +"(var->"+var_name + " == var->"+var_name[:-3]+") && \n"
            placeholder = '          '

        func_enc = func_enc[:-5] + ");\n}\n\n"
        return func_enc

    def encode_func_still(self):
        func_enc = "void still(struct realVar *rvar){\n"

        for var_name in self.predicates_lits_out:
            func_enc += "  rvar->" + var_name + "__1 = rvar->" + var_name + ";\n"

        func_enc += "}\n\n"
        return func_enc

    def encode_func_real2bool(self):
        func_enc = "void real2bool(struct boolVar *bvar, struct realVar *rvar){\n"
        predicates = self.specDFA.getPredicates()

        # create local real var
        for var_name in self.predicates_lits:
            func_enc += "  float " + var_name + " = rvar->" + var_name + ";\n"

        # copy bool var
        for var_name in self.inputNames_:
            if var_name in predicates:
                func_enc += "  bvar->" + var_name + "= (" + predicates[var_name] + ");\n"
            else:
                func_enc += "  bvar->" + var_name + "= rvar->" + var_name + ";\n"


        func_enc += "}\n\n"
        return func_enc

    def encode_func_lr(self):
        func_enc = "void linearReg(struct realVar *rvar, struct hist_t *hist){\n"
        for var_name in self.predicates_lits_out:
            func_enc += "  rvar->" + var_name + "__1 = compute(hist->" + var_name + "__1, "\
                    + str(self.hist_len) + ");\n"

        func_enc += "}\n\n"
        return  func_enc

    def encode_func_updateHis(self):
        func_enc = "void updateHis(struct realVar *var, struct hist_t *hist){\n"
        for var_name in self.predicates_lits_out:
            func_enc += "  for(int i=0; i < " + str(self.hist_len-1) + "; i++) " \
                        "hist->" + var_name + "__1[i] = hist->" + var_name + "__1[i+1];\n"
            func_enc += "  hist->" + var_name + "__1[" + str(self.hist_len-1) + "] = var->" + var_name +"__1;\n"

        func_enc += "}\n\n"
        return func_enc

    def encode_main_shield(self):


        main_enc =r'''
int main(int argc,char *argv[]){
  char* path = argv[1];
  printf("path:%s\n", path);
  int test_num = atoi(argv[2]);
  printf("num of test points:%d\n", test_num);
  int i;
  FILE *fp = fopen(path, "r");
  if ( !fp ) 
  {
      fprintf(stderr, "! Error: faild to open file \n" );
      return -1;
  }
  
  gctx = mk_context();
  gsolver = mk_solver(gctx);
  clock_t start, end;
  
  char buffer[100];
  fgets(buffer, 100, fp); // skip first line
 
  struct realVar *realv = malloc(test_num * sizeof(struct realVar));
'''


        numberofbool = 0;
        numberoffloat =0;
        declare = '  int '
        assign = '    '
        target = ''
        # declare input and output variables
        for var_name in self.inputNames_:
            if var_name not in self.specDFA.getPredicates():
                numberofbool = numberofbool+1
                declare += 'b_' + var_name +', '
                assign += "realv[i]." + var_name +' = b_' + var_name + '; '
                target += '&b_' + var_name + ', '
        # for var_name in self.outputNames_:
        #     if var_name[:-3] not in self.specDFA.getPredicates():
        #         numberofbool = numberofbool + 1
        #         declare += 'b_' + var_name + ', '
        #         assign += "realv[i]." + var_name + ' = b_' + var_name + '; '
        #         target += '&b_' + var_name + ', '

        assign += '\n    '

        if numberofbool < 1:
            declare = '  float '
        else:
            declare = declare[:-2] + ';\n  float '
        for var_name in self.predicates_lits:
            numberoffloat = numberoffloat + 1
            declare += 'f_' + var_name + ', '
            assign += "realv[i]." + var_name + ' = f_' + var_name + '; '
            target += '&f_' + var_name + ', '


        fromat = "%d "*numberofbool + "%f "*numberoffloat
        main_enc += declare[:-2] + ';\n'
        main_enc += r'''
  for(i=0;i < test_num; i++)
  {
    if (feof(fp))
    {
      fprintf(stderr, "! Error: file format invalid!\n" );
      return -1;
    } 
'''
        main_enc += '    fscanf(fp, "' + fromat[:-1] + '", ' + target[:-2] + ');\n'
        main_enc += assign

        main_enc += r'''
  }
  fclose(fp);

  for(i=0;i < test_num; i++){
    start = clock();
    realShield(&realv[i]);
    end = clock() - start;

    if (realv[i].result == 0)
      printf("linear took %ld us.\n", end); 
    else if (realv[i].result == 1)
      printf("lp solver took %ld us.\n", end); 
    else
      printf("non-interfer took %ld us.\n", end); 
    // printf("new u is %f.\n", realv[i].u__1);
  }
}
        
        '''
        return main_enc

    def encode_model(self, num_of_bits, tmp_count):
        mod = 'int shield( struct boolVar *var){\n'

        # encode temporary variables (wires)
        for statePos in range(0, num_of_bits):
            state_wire = "s" + str(statePos) + "n"
            mod += "  bool " + state_wire + " = 0;\n"

        for i in range(1, tmp_count):
            tmp_wire = "tmp" + str(i)
            mod += "  bool " + tmp_wire + " = 0;\n"

        # encode regs
        for statePos in range(0, num_of_bits):
            state = "s" + str(statePos)
            mod += "  static bool " + state + " = 0;\n"

        mod += self.shieldModel_
        return mod

    def encode_transit(self, num_of_bits):
        mod = '\n  //encode transition state\n'
        for statePos in range(0, num_of_bits):
            mod += "  s" + str(statePos) + " = " "s" + str(statePos) + "n;\n"
        return mod

    def encode_func_lp(self):

        func_enc = "int lp(struct boolVar *bvar, struct realVar *rvar){\n"

        func_enc += self.solver_init()
        self.count = 0
        assertions = '  //assert predicates constrains\n'
        for var_name in self.predicates_out:
            assertion, ast = self.solver_assert(self.predicates[var_name])
            assertion += '  if(bvar->' + var_name+'__1) Z3_solver_assert(gctx, gsolver,' + ast + ');\n'
            assertion += '  else Z3_solver_assert(gctx, gsolver, Z3_mk_not(gctx,' + ast + '));\n\n'
            assertions += assertion

        assertions += '  Z3_solver_push(gctx, gsolver);  //checkpoint for backtracking\n\n  //check linear reg result\n'

        for lit in self.predicates_lits_out:
            assertions += '  Z3_solver_assert(gctx, gsolver, Z3_mk_eq(gctx,'+ lit + ', Z3_mk_real(gctx, (int)(rvar->' +lit + '__1*1000), 1000)));\n'

        func_enc += assertions
        func_enc += self.solver_check()
        func_enc += "}\n\n"
        return func_enc


    def solver_init(self):

        init = '  Z3_model m = 0;\n'
        init += '  Z3_ast args[2];\n'
        init += '  int64_t num, den;\n  Z3_ast v;\n'
        init += '  Z3_solver_push(gctx, gsolver);  //checkpoint with a clean solver\n'
        for lit in self.predicates_lits_out:
            init += '  Z3_ast ' + lit + ' = mk_real_var(gctx, "' + lit + '");\n'

        return init+"\n"

    def solver_cc(self): # check & clean solver
        check = '  check(gctx, gsolver);\n'
        check += '  del_solver(gctx, gsolver);\n'
        check += '  Z3_del_context(gctx);\n'
        check += '\n}\n'
        return check

    def solver_check(self):  # check feasibility
        check = '''
  if (Z3_solver_check(gctx, gsolver) == Z3_L_TRUE){
    Z3_solver_pop(gctx, gsolver, 2); // reset solver to empty assertions
    //printf("sat with linear reg algo.\\n");
    return 0;
  }
  else{
    Z3_solver_pop(gctx, gsolver, 1); // remove linear reg constrains
    // try to solve lp directly
    if (Z3_solver_check(gctx, gsolver) == Z3_L_TRUE){
      m = Z3_solver_get_model(gctx, gsolver);
      //assign model to realVar
'''
        for lit in self.predicates_lits_out:
            check += '      if(Z3_model_eval(gctx, m, ' + lit +', 1, &v)){\n'
            check += '        Z3_get_numeral_rational_int64(gctx, v,&num, &den);\n'
            check += '        rvar->' + lit + '__1 = ((float)num)/((float)den);\n'
            check += '      }\n'
            check += '      else{\n'
            check += '         printf("Error: failed to eval model.\\n");\n'
            check += '        //fail to eval\n'
            check += '      }\n'

        check += '''
      Z3_solver_pop(gctx, gsolver, 1); // reset solver to empty assertions
      //printf("sat\\n%s\\n", Z3_model_to_string(gctx, m));
      return 1;
    }
    else{
      Z3_solver_pop(gctx, gsolver, 1); // reset solver to empty assertions
      printf("Error: failed to get real value.\\n");
      return 2;
    }
  }\n'''
        return check

    def solver_assert(self, predicate):
        ast_name = ''

        if predicate.getType()==3:
            lassertion, last = self.solver_assert(predicate.getLeft())
            rassertion, rast = self.solver_assert(predicate.getRight())
            assertion = lassertion + rassertion
            ret = self.op2api(predicate.getValue(), last, rast)
            assertion += ret[0]
            ast_name = 'ast_' + str(self.count)
            assertion += '  Z3_ast ' + ast_name + ' = ' + ret[1]
            self.count += 1

        elif predicate.getType() == 0:# fix: mk_int_var
            assertion = ''
            ast_name = predicate.getValue()
        elif predicate.getType() == 1:
            ast_name = 'ast_' + str(self.count)
            assertion = '  Z3_ast ' + ast_name + ' = mk_int(gctx, ' + predicate.getValue() + ');\n'
            self.count += 1
        elif predicate.getType() == 2:
            ast_name = 'ast_' + str(self.count)
            assertion = '  Z3_ast ' + ast_name + ' = Z3_mk_numeral(gctx, "' + predicate.getValue() + '",Z3_mk_real_sort(gctx));\n'
            self.count += 1


        return assertion, ast_name


    def op2api(self, op, left, right):
        ret = ['', '']

        if op == '+':
            ret[0] = '  args[0] = ' + left + ';\n  args[1] = ' + right + ';\n'
            ret[1] = 'Z3_mk_add(gctx, 2, args);\n'
        elif op == '-':
            ret[0] = '  args[0] = ' + left + ';\n  args[1] = ' + right + ';\n'
            ret[1] = 'Z3_mk_sub(gctx, 2, args);\n'
        elif op == '*':
            ret[0] = '  args[0] = '+ left + ';\n  args[1] = ' + right + ';\n'
            ret[1] = 'Z3_mk_mul(gctx, 2, args);\n'
        elif op == '/':
            ret[1] = 'Z3_mk_div(gctx,' + left + ',' + right + ');\n'
        elif op == '&' or op == '&&':
            ret[0] = '  args[0] = ' + left + ';\n  args[1] = ' + right + ';\n'
            ret[1] = 'Z3_mk_and(gctx, 2, args);\n'
        elif op == '|' or op == '||':
            ret[0] = '  args[0] = '+ left + ';\n  args[1] = ' + right + ';\n'
            ret[1] = 'Z3_mk_or(gctx, 2, args);\n'
        elif op == '%':
            ret[1] = 'Z3_mk_rem(gctx,' + left + ',' + right + ');\n'
        # elif op == 'mod':
        #     ret[1] = 'Z3_mk_mod(gctx,'+ left + ',' + right + ');\n'
        elif op == '^':
            ret[1] = 'Z3_mk_pow(gctx,'+ left + ',' + right + ');\n'
        elif op == '>':
            ret[1] = 'Z3_mk_gt(gctx,'+ left + ',' + right + ');\n'
        elif op == '>=':
            ret[1] = 'Z3_mk_ge(gctx,' + left + ',' + right + ');\n'
        elif op == '<':
            ret[1] = 'Z3_mk_lt(gctx,' + left + ',' + right + ');\n'
        elif op == '<=':
            ret[1] = 'Z3_mk_le(gctx,' + left + ',' + right + ');\n'
        elif op == '==':
            ret[1] = 'Z3_mk_eq(gctx,' + left + ',' + right + ');\n'
        else:
            raise SyntaxError('Invalid operator in predicates!')
        return ret




